always-run:
  script: echo 'this should always run'

on-pull-requests:
  stage: test
  script:
    - pip install pylint
    - pylint -d C0103 app

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
