always-run:
  script: echo 'this should always run'

on-pull-requests:
  stage: test
  script:
    - pylint app

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
